@echo off
echo Starting Frontend HTTP Server...
cd /d "C:\Users\lbi\OneDrive - Stiftung Myclimate\Dokumente\Privat\AI\WebDev\Voicepartnerai.com"

echo Checking if Python is available...
python --version >nul 2>&1
if %errorlevel% == 0 (
    echo Using Python HTTP Server on port 8000...
    echo Open: http://localhost:8000/workflow-app.html
    python -m http.server 8000
) else (
    echo Python not found, using Node.js serve...
    echo Installing serve globally...
    npm install -g serve
    echo Starting serve on port 8000...
    echo Open: http://localhost:8000/workflow-app.html
    serve . -p 8000
)